language: java
jdk:
  - openjdk11
deploy:
  provider: releases
  file_glob: true
  file: out/artifacts/axolotl*.jar
  api_key: $GITHUB_API_KEY
  skip_cleanup: true
  on:
    tags: true
after_success:
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"