language: java
jdk:
- openjdk11
sudo: true
deploy:
  provider: releases
  api_key:
    secure: gRKOf0MlnrjZTbP4qE3lanZ1xssdzGgJ6b2ojYlJ0akokxmytXZOtRd7DkLRP4moHY1IPVhLMjx4PIFie6S+WFzL5/4jbladwYjScMFJlZiWXt63BCBQGtc8ggq8U7BH9Lh07umm/OIBzjPC9SPLw1SMguiv+XmSVKvsF8cX19pMBlBvN/YNZyDM8X0RRNLmtJBPVyLfhRVgKZ9CcXCpEXDRX1Lakx1rhsDUAvy6KzomkZzMH0g9J5xPwCgQ78zjSX6j7eGqan9XnRmq09KiOFGt3iuoEwNLH/+L9SvdmA14GCWC8b5DYwE5FalaFOz5aHSxqmULizXh/6JYpcbzRv+b/qze/V62MZ3CgnjyeNtONrH9XFDWmPUeni9ytpwS9Tf/hLxuuA8crlcGAapVkY3OjrCisIHHSrBx/hanTnP085ER7Bueus8k3YyG16PSQDazZqqzvXJApeEjnqXS0EOd75vk4ap0dMBJxhesJE/B84kHT1RRZAX8sd4VLJ06MyM5i7BJDA9/fuQfHWiw1F0Zkjs6oM6zlEnZC6Ke1i33fK4qEAbC5zTCG7J5yfuNY5Yrre8Qe/VYFqgKHS2UGAnoF20dCeDM6m4//pkaE2pInBXOHcCyI27F4cJS1F/EaCR8iVZFEEbKTq6KW/3YZ+07BjMnFVgTrkJYr0n/PoU=
  file: axolotl.jar
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: louism33/Axolotl
env:
  global:
    secure: lnA6Uhw4jhLqCaAwCOe9+VVUkYEixBg2vVHBCm/IRy9ykXCtfcLuE+3Mr4KDxfqR5cU5vZSRN1SDPy7hnpHGo2ginDa38MoJEZCuGUtjDL5qC+ofxU/VHf9hoEhuf/GCZ+duLbVKA9Rnx9sOWRFsuzFf7LFzawByHYb/fqcmkmvlxAIIULO3AXlf9cZW8MGi7uJP/9NeRCfVazHvofXjF2StOEVO7OXLBgmFz15NqTii/3m71l0yGwUflnJTRLJH8zoVjeGXQdjHvi/ukh4eZhOcYvwrhmmjh0KvRfd43WtjLYKOhdt/Jq09o5bmFQ+oU6siSH0oEJJ3uX1fbKbnRAPT+fd9e+SC6lQ50FLM/OAFp+uBRWF8d+quf0kRugsxO+qkXD1Ns0gtAs5La6Ohxg8RTXcZ71+Z9cKVercTPbptu61nuOGcvVz5HMjQs603hBrw+U/V+t7yMXzVYJLSDiX+r4ejWl5BGwuCLUiu7VEbhZ1jInH8iPT3G4ehl2WulDbOnLzhFe0MswBgwGHjnNSu8eKQzfeuR2iT9h+avjirCBzH7CnFnH3TH1vCvUukgvaK2e3Lg5tO9AxkN/RtkdxWmd/QrsXNwpJ6JdqzLxXo1B3GLcDPbQhXTmsPJQjLUiy/UF+N4KYC5tKkLh4YLNFlV1JBDyA1+zLHYfixkhs=


