language: java
jdk:
- openjdk11
sudo: true
deploy:
  provider: releases
  api_key:
    secure: jf9yXV4LUGM0ayfdIcag7wgtwzrK6KBlCaITkA19ldU6YprpeFw3eyzWSBRKeQ6vKhIXrZdjpv04NJQndB3UewYUSK3NkvVJNmLW8fDwcT0nAvAsHAJL1i1MIVe/ncGdntHGHlmoKd8GejFbs8c44FwU/LT6B8TK+TUhooHXQF8uixXySyNmTEUNQooRYJ1wH/YYFf+XG+gms7rHTbpmekm9AdrPsotYzYgdkwZye4a24LsaXDjUbhf/xmNJZ4IeBAlUTnauS1OIeoFiDNOhxy7QvM2dlGzVS8t04tSblzh6IOnwg8DT9UsbTl6pM9WtXj90OhssVxx+XV7nLrAwssK+h/E5JFlXv0pVAix77VezUbkXsbh83jPcSiNIzuUUJd0N0rsY+c4+22UMEHDNtZHsAUQg96c9abFeO1sHaHWMm8hKrMLKCQyYeFY2dwQDEJv57wJq/tHMRllUOy3BWuhLb9BB/2uZGL4Z9xbiLvBHlHYf3k2Z8KsifK3cmB84/iW6dOQUoPLdI5lfqIEQ/vBN2YfdypNf8eXQkD1glgknso66K6iTUkEn5uLkWK9fx6eQxvLT+OK0zZUB30MK99JY1pRN9YPQE8D+plGDzSgCw3aOOVXbPT4We/YAsFc70RCzYKrLIu1UJ1frkrTxHmfbSfB67L2XWbipVk+6D2M=
  file: axolotl_v*.jar
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: louism33/Axolotl
    branch: develop