language: java
jdk:
  - openjdk11
  -
deploy:
  provider: releases
  api_key:
    secure: gRKOf0MlnrjZTbP4qE3lanZ1xssdzGgJ6b2ojYlJ0akokxmytXZOtRd7DkLRP4moHY1IPVhLMjx4PIFie6S+WFzL5/4jbladwYjScMFJlZiWXt63BCBQGtc8ggq8U7BH9Lh07umm/OIBzjPC9SPLw1SMguiv+XmSVKvsF8cX19pMBlBvN/YNZyDM8X0RRNLmtJBPVyLfhRVgKZ9CcXCpEXDRX1Lakx1rhsDUAvy6KzomkZzMH0g9J5xPwCgQ78zjSX6j7eGqan9XnRmq09KiOFGt3iuoEwNLH/+L9SvdmA14GCWC8b5DYwE5FalaFOz5aHSxqmULizXh/6JYpcbzRv+b/qze/V62MZ3CgnjyeNtONrH9XFDWmPUeni9ytpwS9Tf/hLxuuA8crlcGAapVkY3OjrCisIHHSrBx/hanTnP085ER7Bueus8k3YyG16PSQDazZqqzvXJApeEjnqXS0EOd75vk4ap0dMBJxhesJE/B84kHT1RRZAX8sd4VLJ06MyM5i7BJDA9/fuQfHWiw1F0Zkjs6oM6zlEnZC6Ke1i33fK4qEAbC5zTCG7J5yfuNY5Yrre8Qe/VYFqgKHS2UGAnoF20dCeDM6m4//pkaE2pInBXOHcCyI27F4cJS1F/EaCR8iVZFEEbKTq6KW/3YZ+07BjMnFVgTrkJYr0n/PoU=
  file: axolotl.jar
  on:
    tags: true
    repo: louism33/Axolotl